import type { HudScene } from "@/components/hud-scene";

export const finValStudioScene: HudScene = {
  id: "finval-engine",
  title: "VALUATION ENGINE",
  subtitle: "FinVal-Studio · assemblage complet",
  theme: "graphite",
  updatedAt: "2026-08-24T09:12:00Z",
  status: [
    { label: "MODE", value: "DCF + COMPS", severity: "nominal" },
    { label: "ITER", value: "10 000", severity: "nominal" },
    { label: "DRIFT", value: "2,4 %", severity: "watch" },
  ],
  core: {
    metaphor: "turbine de valorisation à étages empilés",
    axis: "vertical",
    explosion: 0.72,
    parts: [
      {
        id: "inputs",
        index: 1,
        label: "Jeu d'hypothèses",
        shape: "disc",
        offset: 0.08,
        scale: 0.7,
        callout: { side: "left", text: "Hypothèses", detail: "42 variables" },
        panelRef: "sensitivity",
      },
      {
        id: "cashflows",
        index: 2,
        label: "Projection de flux",
        shape: "disc",
        offset: 0.3,
        scale: 0.9,
        callout: { side: "left", text: "Flux projetés", detail: "horizon 7 ans" },
      },
      {
        id: "discount",
        index: 3,
        label: "Noyau d'actualisation",
        shape: "core",
        offset: 0.5,
        scale: 1,
        severity: "nominal",
        callout: { side: "right", text: "WACC", detail: "8,6 %" },
        panelRef: "wacc",
      },
      {
        id: "montecarlo",
        index: 4,
        label: "Couronne Monte-Carlo",
        shape: "ring",
        offset: 0.72,
        scale: 1.1,
        severity: "watch",
        callout: { side: "right", text: "Monte-Carlo", detail: "10 000 tirages" },
        panelRef: "distribution",
      },
      {
        id: "output",
        index: 5,
        label: "Fourchette de valeur",
        shape: "shell",
        offset: 0.94,
        scale: 0.8,
        callout: { side: "left", text: "Valeur d'entreprise" },
        panelRef: "range",
      },
    ],
  },
  panels: [
    {
      id: "sensitivity",
      kind: "sparkline",
      title: "Sensibilité au WACC",
      column: "left",
      series: [62, 58, 55, 51, 48, 46, 43, 41, 40, 38],
      current: 38,
      unit: "M€",
      demo: true,
    },
    {
      id: "wacc",
      kind: "radial",
      title: "Coût du capital",
      column: "left",
      value: 0.86,
      label: "8,6 %",
      thresholds: [0.6, 0.9],
      demo: true,
    },
    {
      id: "distribution",
      kind: "bars",
      title: "Distribution des tirages",
      column: "right",
      bars: [
        { label: "P10", value: 0.22 },
        { label: "P25", value: 0.48 },
        { label: "P50", value: 1 },
        { label: "P75", value: 0.61 },
        { label: "P90", value: 0.19, severity: "watch" },
      ],
      demo: true,
    },
    {
      id: "range",
      kind: "readout",
      title: "Fourchette retenue",
      column: "right",
      rows: [
        { label: "Bas", value: "31,4 M€" },
        { label: "Central", value: "38,0 M€", severity: "nominal" },
        { label: "Haut", value: "47,9 M€" },
        { label: "Écart-type", value: "4,1 M€", severity: "watch" },
      ],
      demo: true,
    },
  ],
  bom: [
    { index: 1, ref: "ASM-01", label: "Jeu d'hypothèses", qty: "42 var." },
    { index: 2, ref: "ASM-02", label: "Projection de flux", qty: "7 ans" },
    { index: 3, ref: "ASM-03", label: "Noyau d'actualisation", qty: "1" },
    { index: 4, ref: "ASM-04", label: "Couronne Monte-Carlo", qty: "10 000" },
    { index: 5, ref: "ASM-05", label: "Fourchette de valeur", qty: "3 bornes" },
  ],
};
